In [1]:
import numpy as np
np.__version__

'1.18.1'

In [2]:
np?

In [3]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(L[0])

int

In [5]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [6]:
type(L2[0])

str

In [7]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [8]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [10]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [11]:
np.array([1, 2, 3], dtype='float32')

array([1., 2., 3.], dtype=float32)

In [12]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [13]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
np.random.random((3, 3))

array([[4.37472183e-01, 2.23579205e-01, 2.10674552e-01],
       [7.97302242e-01, 3.67989812e-02, 2.83442025e-01],
       [2.48146401e-01, 2.18808807e-04, 2.99590013e-01]])

In [19]:
np.random.normal(0, 1, (3, 3))

array([[ 0.96761359,  1.1644573 , -1.56250657],
       [ 0.76132417, -1.42999855, -0.62783809],
       [-0.39717348,  2.50263386, -0.97365083]])

In [20]:
np.random.randint(0, 10, (3, 3))

array([[6, 7, 6],
       [9, 6, 2],
       [1, 5, 6]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.empty(3)

array([1., 1., 1.])

In [23]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [24]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [25]:
print("dtype: ", x3.dtype)

dtype:  int64


In [26]:
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes: ", x3.nbytes, "bytes")

itemsize:  8 bytes
nbytes:  480 bytes


In [27]:
x1

array([5, 0, 3, 3, 7, 9])

In [28]:
x1[0]

5

In [29]:
x1[4]

7

In [30]:
x1[-1]

9

In [31]:
x1[-2]

7

In [32]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [33]:
x2[0, 0]

3

In [34]:
x2[2, 0]

1

In [35]:
x2[2, -1]

7

In [36]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [37]:
x1[0] = 2.7182818
x1

array([2, 0, 3, 3, 7, 9])

In [38]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
x[:5]

array([0, 1, 2, 3, 4])

In [40]:
x[5:]

array([5, 6, 7, 8, 9])

In [41]:
x[4:7]

array([4, 5, 6])

In [42]:
x[::2]

array([0, 2, 4, 6, 8])

In [43]:
x[1::2]

array([1, 3, 5, 7, 9])

In [44]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [45]:
x[5::-2]

array([5, 3, 1])

In [46]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [47]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [48]:
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [49]:
x2[:, 0]

array([12,  7,  1])

In [50]:
x2[0, :]

array([12,  5,  2,  4])

In [51]:
x2_sub = x2[:2, :2]
x2_sub

array([[12,  5],
       [ 7,  6]])

In [52]:
x2_sub[0, 0] = 99
x2_sub

array([[99,  5],
       [ 7,  6]])

In [53]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [54]:
x2_copy = x2[:2, :2].copy()
x2_copy

array([[99,  5],
       [ 7,  6]])

In [55]:
x2_copy[0, 0] = 11
x2_copy

array([[11,  5],
       [ 7,  6]])

In [56]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [57]:
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [63]:
x.reshape((1, 3))

array([[1, 2, 3]])

In [64]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [65]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [66]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [69]:
x.reshape((3, -1))

array([[1],
       [2],
       [3]])

In [70]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [71]:
z = [4, 5, 6]
np.concatenate([x, y, z])

array([1, 2, 3, 3, 2, 1, 4, 5, 6])

In [72]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [73]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [74]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [75]:
y = np.array([[99],
             [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [76]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [78]:
grid = np.arange(16).reshape((4, -1))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [79]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [80]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [81]:
grid = np.arange(27).reshape((3, 3, 3))
grid

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [89]:
x1, x2, x3 = np.dsplit(grid, [1, 1])
print(x1, x2, x3)

[[[ 0]
  [ 3]
  [ 6]]

 [[ 9]
  [12]
  [15]]

 [[18]
  [21]
  [24]]] [] [[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
