In [1]:
# 배열 속성 지정: 배열의 크기, 모양, 메모리 소비량, 데이터 타입을 결정한다
# 배열 인덱싱: 개별 배열 요솟값을 가져오고 설정한다
# 배열 슬라이싱: 큰 배열 내에 있는 작은 하위 배열을 가져오고 설정한다
# 배열 재구조화: 해당 배열의 형상을 변경한다
# 배열 결합 및 분할: 여러 배열을 하나로 결합하고 하나의 배열을 여러 개로 분할한다

In [2]:
import numpy as np

np.random.seed(0)

In [10]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [21]:
for i in [x1, x2, x3]:
    print(i)
    print('ndim: ', i.ndim)
    print('shape: ', i.shape)
    print('size: ', i.size)
    print('dtype: ', i.dtype)
    print('itemsize: ', i.itemsize, "bytes")
    print('nbytes: ', i.nbytes, 'bytes')
    print('===============')

[3 5 2 4 7 6]
ndim:  1
shape:  (6,)
size:  6
dtype:  int64
itemsize:  8 bytes
nbytes:  48 bytes
[[8 8 1 6]
 [7 7 8 1]
 [5 9 8 9]]
ndim:  2
shape:  (3, 4)
size:  12
dtype:  int64
itemsize:  8 bytes
nbytes:  96 bytes
[[[4 3 0 3 5]
  [0 2 3 8 1]
  [3 3 3 7 0]
  [1 9 9 0 4]]

 [[7 3 2 7 2]
  [0 0 4 5 5]
  [6 8 4 1 4]
  [9 8 1 1 7]]

 [[9 9 3 6 7]
  [2 0 3 5 9]
  [4 4 6 4 4]
  [3 4 4 8 4]]]
ndim:  3
shape:  (3, 4, 5)
size:  60
dtype:  int64
itemsize:  8 bytes
nbytes:  480 bytes


In [22]:
x1

array([3, 5, 2, 4, 7, 6])

In [23]:
x1[0]

3

In [24]:
x1[7]

IndexError: index 7 is out of bounds for axis 0 with size 6

In [25]:
x1[-1]

6

In [26]:
x1[-5]

5

In [27]:
x1[-7]

IndexError: index -7 is out of bounds for axis 0 with size 6

In [28]:
x2

array([[8, 8, 1, 6],
       [7, 7, 8, 1],
       [5, 9, 8, 9]])

In [29]:
x2[0 ,0]

8

In [30]:
x2[2, 0]

5

In [32]:
x2[1, -1]

1

In [33]:
x2[0, 0] = 12
x2

array([[12,  8,  1,  6],
       [ 7,  7,  8,  1],
       [ 5,  9,  8,  9]])

In [34]:
x1[0] = 3.14159
x1

array([3, 5, 2, 4, 7, 6])

In [35]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
x[:5]

array([0, 1, 2, 3, 4])

In [37]:
x[5:]

array([5, 6, 7, 8, 9])

In [38]:
x[4:7]

array([4, 5, 6])

In [39]:
x[::2]

array([0, 2, 4, 6, 8])

In [40]:
x[1::2]

array([1, 3, 5, 7, 9])

In [41]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [42]:
x[5::-2]

array([5, 3, 1])

In [43]:
x2

array([[12,  8,  1,  6],
       [ 7,  7,  8,  1],
       [ 5,  9,  8,  9]])

In [44]:
x2[:2, :3]

array([[12,  8,  1],
       [ 7,  7,  8]])

In [45]:
x2[:3, ::2]

array([[12,  1],
       [ 7,  8],
       [ 5,  8]])

In [46]:
x2[::-1, ::-1]

array([[ 9,  8,  9,  5],
       [ 1,  8,  7,  7],
       [ 6,  1,  8, 12]])

In [47]:
x2[:, 0]

array([12,  7,  5])

In [48]:
x2[0, :]

array([12,  8,  1,  6])

In [49]:
x2[0]

array([12,  8,  1,  6])

In [50]:
x2[:, 0]

array([12,  7,  5])

In [51]:
x2_sub = x2[:2, :2]
x2_sub

array([[12,  8],
       [ 7,  7]])

In [52]:
x2_sub[0, 0] = 1
x2_sub

array([[1, 8],
       [7, 7]])

In [53]:
x2

array([[1, 8, 1, 6],
       [7, 7, 8, 1],
       [5, 9, 8, 9]])

In [54]:
x2_copy = x2[:2, :2].copy()
x2_copy

array([[1, 8],
       [7, 7]])

In [55]:
x2_copy[0, 0] = 99
x2_copy

array([[99,  8],
       [ 7,  7]])

In [56]:
x2

array([[1, 8, 1, 6],
       [7, 7, 8, 1],
       [5, 9, 8, 9]])

In [57]:
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [63]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [64]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [65]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [66]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [67]:
z = [99, 99, 99]
np.concatenate(x, y, z)

TypeError: only integer scalar arrays can be converted to a scalar index

In [68]:
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [69]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [70]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [71]:
grid = np.array([[9, 8, 7],
                [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [72]:
np.vstack([grid, x])

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [73]:
y = np.array([[11],
             [10]])
np.hstack([y,grid])

array([[11,  9,  8,  7],
       [10,  6,  5,  4]])

In [74]:
np.hstack([grid, y])

array([[ 9,  8,  7, 11],
       [ 6,  5,  4, 10]])

In [75]:
np.vstack([grid, y])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 1

In [76]:
np.hstack([grid, x])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [83]:
z = np.array([[[0],[1],[2]],[[3],[4],[5]], [[6], [7], [8]]])
z

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [84]:
grid = np.arange(27).reshape(3, 3, 3)
grid

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [85]:
np.dstack([z, grid])

array([[[ 0,  0,  1,  2],
        [ 1,  3,  4,  5],
        [ 2,  6,  7,  8]],

       [[ 3,  9, 10, 11],
        [ 4, 12, 13, 14],
        [ 5, 15, 16, 17]],

       [[ 6, 18, 19, 20],
        [ 7, 21, 22, 23],
        [ 8, 24, 25, 26]]])

In [86]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [4 5] [6 7 8 9]


In [88]:
x1, x2, x3, x4 = np.split(x, [3, 5])

ValueError: not enough values to unpack (expected 4, got 3)

In [90]:
x1, x2, x3, x4 = np.split(x, [2, 4, 6])
print(x1, x2, x3, x4)

[1 2] [3 4] [5 6] [7 8 9]


In [91]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [93]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [94]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
