In [1]:
import numpy as np
np.random.seed(0)

In [2]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [3]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

2.26 s ± 391 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [5]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [6]:
%timeit (1.0 / big_array)

1.6 ms ± 173 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [8]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [9]:
x+5

array([5, 6, 7, 8])

In [10]:
x-5

array([-5, -4, -3, -2])

In [11]:
x*2

array([0, 2, 4, 6])

In [12]:
x/2

array([0. , 0.5, 1. , 1.5])

In [13]:
x//2

array([0, 0, 1, 1])

In [14]:
-x

array([ 0, -1, -2, -3])

In [15]:
x ** 2

array([0, 1, 4, 9])

In [16]:
x % 2

array([0, 1, 0, 1])

In [17]:
np.add(x, 2)

array([2, 3, 4, 5])

In [18]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [19]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [20]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [25]:
x = np.array([3-4j, 2+1j, 1, 3.14])
x

array([3.  -4.j, 2.  +1.j, 1.  +0.j, 3.14+0.j])

In [26]:
np.abs(x)

array([5.        , 2.23606798, 1.        , 3.14      ])

In [27]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [28]:
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [30]:
theta = [-1, 0, 1]
print(np.arcsin(theta))
print(np.arccos(theta))
print(np.arctan(theta))

[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


In [32]:
x = [1, 2, 3]
print(np.exp(x))
print(np.exp2(x))
print(np.power(4, x))

[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]
[ 4 16 64]


In [33]:
x = [1, 2, 4, 10]
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[0.         0.69314718 1.38629436 2.30258509]
[0.         1.         2.         3.32192809]
[0.         0.30103    0.60205999 1.        ]


In [34]:
x = [0, 0.001, .01, .1]
print(np.expm1(x))
print(np.log1p(x))

[0.         0.0010005  0.01005017 0.10517092]
[0.         0.0009995  0.00995033 0.09531018]


In [35]:
from scipy import special

In [38]:
x = [1, 5, 10]
print(special.gamma(x))
print(special.gammaln(x))
print(special.beta(x, 2))

[1.0000e+00 2.4000e+01 3.6288e+05]
[ 0.          3.17805383 12.80182748]
[0.5        0.03333333 0.00909091]


In [39]:
x = np.array([0, 0.3, .7, 1.])
print(special.erf(x))
print(special.erfc(x))
print(special.erfinv(x))

[0.         0.32862676 0.67780119 0.84270079]
[1.         0.67137324 0.32219881 0.15729921]
[0.         0.27246271 0.73286908        inf]


In [40]:
x = np.arange(5)
y = np.empty(5)
print(y)
np.multiply(x, 10, out=y)
print(y)

[ 5.  2.  1.  3. 14.]
[ 0. 10. 20. 30. 40.]


In [41]:
y = np.zeros(10)
print(y)
np.power(2, x, out=y[::2])
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [42]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [43]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [44]:
np.sum.accumulate(x)

AttributeError: 'function' object has no attribute 'accumulate'

In [45]:
np.sum(x)

15

In [46]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [47]:
np.add.outer(x, x)

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [48]:
np.add.outer(x,x,x)

TypeError: exactly two arguments expected