In [1]:
import numpy as np
np.__version__

'1.18.1'

In [2]:
np?

In [3]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(L[0])

int

In [5]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [6]:
type(L2[0])

str

In [7]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [8]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [10]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [11]:
np.array([1, 2, 3], dtype='float32')

array([1., 2., 3.], dtype=float32)

In [12]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [13]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
np.random.random((3, 3))

array([[0.19927414, 0.74812231, 0.19215227],
       [0.50985531, 0.95389333, 0.12739082],
       [0.60195954, 0.09486231, 0.28015529]])

In [19]:
np.random.normal(0, 1, (3, 3))

array([[ 0.15657491,  0.74708423,  0.83935958],
       [-1.19321247,  0.00864649,  0.53069901],
       [ 1.54276131,  0.19745829, -0.95431194]])

In [20]:
np.random.randint(0, 10, (3, 3))

array([[4, 8, 8],
       [0, 5, 6],
       [9, 8, 6]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.empty(3)

array([1., 1., 1.])

In [23]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [24]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [25]:
print("dtype: ", x3.dtype)

dtype:  int64


In [26]:
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes: ", x3.nbytes, "bytes")

itemsize:  8 bytes
nbytes:  480 bytes


In [27]:
x1

array([5, 0, 3, 3, 7, 9])

In [28]:
x1[0]

5

In [29]:
x1[4]

7

In [30]:
x1[-1]

9

In [31]:
x1[-2]

7

In [32]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [33]:
x2[0, 0]

3

In [34]:
x2[2, 0]

1

In [35]:
x2[2, -1]

7

In [36]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [38]:
x1[0] = 2.7182818
x1

array([2, 0, 3, 3, 7, 9])

In [39]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
x[:5]

array([0, 1, 2, 3, 4])

In [41]:
x[5:]

array([5, 6, 7, 8, 9])

In [42]:
x[4:7]

array([4, 5, 6])

In [43]:
x[::2]

array([0, 2, 4, 6, 8])

In [44]:
x[1::2]

array([1, 3, 5, 7, 9])