In [1]:
import numpy as np
np.__version__

'1.18.1'

In [3]:
np?

In [4]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
type(L[0])

int

In [6]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
type(L2[0])

str

In [8]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [9]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [11]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [12]:
np.array([1, 2, 3], dtype='float32')

array([1., 2., 3.], dtype=float32)

In [13]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [14]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [17]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.random.random((3, 3))

array([[0.48379503, 0.05273302, 0.22927956],
       [0.4245075 , 0.66455861, 0.77670125],
       [0.64148483, 0.59378795, 0.21777902]])

In [20]:
np.random.normal(0, 1, (3, 3))

array([[-0.72965575,  0.82885879,  0.05006806],
       [ 0.89281017, -1.01571374,  2.24192535],
       [-0.82450602,  0.9733961 , -0.10698528]])

In [21]:
np.random.randint(0, 10, (3, 3))

array([[6, 6, 3],
       [4, 3, 6],
       [0, 3, 6]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.empty(3)

array([1., 1., 1.])