In [1]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [2]:
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [3]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.7 s ± 41.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [5]:
%timeit (1.0 / big_array)

1.4 ms ± 16.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [7]:
x = np.arange(9).reshape((3, 3))
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [8]:
x = np.arange(4)
print(x)
print(x + 5)
print(x - 5)
print(x * 2)
print(x / 2)
print(x // 2)

[0 1 2 3]
[5 6 7 8]
[-5 -4 -3 -2]
[0 2 4 6]
[0.  0.5 1.  1.5]
[0 0 1 1]


In [9]:
np.add(x, 2)

array([2, 3, 4, 5])

In [10]:
np.subtract(x, 2)

array([-2, -1,  0,  1])

In [11]:
np.negative(x)

array([ 0, -1, -2, -3])

In [12]:
np.multiply(x, 2)

array([0, 2, 4, 6])

In [13]:
np.divide(x, 2)

array([0. , 0.5, 1. , 1.5])

In [14]:
np.floor_divide(x, 2)

array([0, 0, 1, 1])

In [15]:
np.power(x, 3)

array([ 0,  1,  8, 27])

In [16]:
np.mod(x, 3)

array([0, 1, 2, 0])

In [17]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [18]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [19]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [20]:
x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
np.abs(x)

array([5., 5., 2., 1.])

In [21]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [22]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [23]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [24]:
x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
np.abs(x)

array([5., 5., 2., 1.])

In [25]:
theta = np.linspace(0, np.pi, 3)

In [27]:
theta

array([0.        , 1.57079633, 3.14159265])

In [28]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [29]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [30]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [31]:
x = [-1, 0, 1]
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

In [32]:
np.arccos(x)

array([3.14159265, 1.57079633, 0.        ])

In [33]:
np.arctan(x)

array([-0.78539816,  0.        ,  0.78539816])

In [34]:
x = [1, 2, 3]

In [35]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [36]:
np.exp2(x)

array([2., 4., 8.])

In [37]:
np.power(3, x)

array([ 3,  9, 27])

In [38]:
x = [1, 2, 4, 10]

In [39]:
np.log(x)

array([0.        , 0.69314718, 1.38629436, 2.30258509])

In [40]:
np.log2(x)

array([0.        , 1.        , 2.        , 3.32192809])

In [41]:
np.log10(x)

array([0.        , 0.30103   , 0.60205999, 1.        ])

In [42]:
x = [0, 0.001, 0.01, 0.1]

In [43]:
np.expm1(x)

array([0.        , 0.0010005 , 0.01005017, 0.10517092])

In [44]:
np.log1p(x)

array([0.        , 0.0009995 , 0.00995033, 0.09531018])

In [45]:
np.expm1(x) + np.log1p(x)

array([0.       , 0.002    , 0.0200005, 0.2004811])

In [46]:
from scipy import special

In [47]:
x = [1, 5, 10]
special.gamma(x)

array([1.0000e+00, 2.4000e+01, 3.6288e+05])

In [48]:
special.gammaln(x)

array([ 0.        ,  3.17805383, 12.80182748])

In [49]:
special.beta(x, 2)

array([0.5       , 0.03333333, 0.00909091])

In [50]:
x = np.array([0, 0.3, 0.7, 1.0])
special.erf(x)

array([0.        , 0.32862676, 0.67780119, 0.84270079])

In [51]:
special.erfc(x)

array([1.        , 0.67137324, 0.32219881, 0.15729921])

In [52]:
special.erfinv(x)

array([0.        , 0.27246271, 0.73286908,        inf])

In [55]:
x = np.arange(5)
y = np.empty(5)
print(y)
np.multiply(x, 10, out=y)

[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323]


array([ 0., 10., 20., 30., 40.])

In [54]:
y

array([ 0., 10., 20., 30., 40.])

In [56]:
y = np.zeros(10)
np.power(2, x, out=y[::2])

array([ 1.,  2.,  4.,  8., 16.])

In [57]:
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [58]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [59]:
np.multiply.reduce(x)

120

In [60]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [61]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [62]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [63]:
import numpy
numpy?