In [1]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [2]:
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [3]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.73 s ± 20.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [5]:
%timeit (1.0 / big_array)

1.46 ms ± 48.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [7]:
x = np.arange(9).reshape((3, 3))
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [9]:
x = np.arange(4)
print(x)
print(x + 5)
print(x - 5)
print(x * 2)
print(x / 2)
print(x // 2)

[0 1 2 3]
[5 6 7 8]
[-5 -4 -3 -2]
[0 2 4 6]
[0.  0.5 1.  1.5]
[0 0 1 1]


In [10]:
np.add(x, 2)

array([2, 3, 4, 5])

In [11]:
np.subtract(x, 2)

array([-2, -1,  0,  1])

In [12]:
np.negative(x)

array([ 0, -1, -2, -3])

In [13]:
np.multiply(x, 2)

array([0, 2, 4, 6])

In [14]:
np.divide(x, 2)

array([0. , 0.5, 1. , 1.5])

In [15]:
np.floor_divide(x, 2)

array([0, 0, 1, 1])

In [16]:
np.power(x, 3)

array([ 0,  1,  8, 27])

In [17]:
np.mod(x, 3)

array([0, 1, 2, 0])