In [1]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
type(L[0])

int

In [3]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [4]:
type(L2[0])

str

In [5]:
L3 = [True, "1", 0, 2.71828]
L3

[True, '1', 0, 2.71828]

In [6]:
[type(item) for item in L3]

[bool, str, int, float]

In [7]:
import array

In [8]:
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
import numpy as np

In [10]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [11]:
print(In[10])

np.array([1, 4, 2, 5, 3])


In [12]:
print(Out[10])

[1 4 2 5 3]


In [13]:
np.array([3.14, 4, 2])

array([3.14, 4.  , 2.  ])

In [14]:
np.array([1, 2, 3], dtype='float32')

array([1., 2., 3.], dtype=float32)

In [15]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [16]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.zeros((10,1), dtype=int)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [19]:
np.zeros((1, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [21]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
np.random.random((3, 3))

array([[0.53190437, 0.06174846, 0.4256922 ],
       [0.25186538, 0.31166404, 0.9682426 ],
       [0.14050887, 0.11135079, 0.27851371]])

In [24]:
np.random.normal(0, 1, (3, 3))

array([[ 0.61687134, -0.58850234,  1.12839712],
       [-0.33818535,  0.09660275,  1.69243011],
       [ 0.86943765,  1.08313903,  0.85460173]])

In [25]:
np.random.randint(0, 10, (3, 3))

array([[4, 4, 2],
       [8, 5, 5],
       [6, 5, 0]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.empty(3)

array([1., 1., 1.])

In [28]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [30]:
np.empty((3, 3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.empty((4,2))

array([[4.64076929e-310, 0.00000000e+000],
       [2.37663529e-312, 2.56761491e-312],
       [8.48798317e-313, 9.33678148e-313],
       [8.70018275e-313, 2.02566915e-322]])