In [1]:
import numpy as np
import pandas as pd

In [2]:
def make_df(cols, ind):
    """빠르게 DataFrame을 생성"""
    data = {c: [str(c) + str(i) for i in ind]
               for c in cols}
    return pd.DataFrame(data, ind)

In [3]:
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [4]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x = [[1, 2],
    [3, 4]]
np.concatenate([x, x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [6]:
np.concatenate([x, x], axis=0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [8]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [9]:
df1 = make_df('AB', [1, 2])
df2 = make_df('CD', [3, 4])
print(df1); print(df2); print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2
    C   D
3  C3  D3
4  C4  D4
     A    B    C    D
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   C3   D3
4  NaN  NaN   C4   D4


In [10]:
pd.concat([df1, df2], axis=1)

A    B    C    D
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   C3   D3
4  NaN  NaN   C4   D4

In [11]:
pd.concat([df1, df2], axis=0)

A    B    C    D
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   C3   D3
4  NaN  NaN   C4   D4

In [14]:
df3 = make_df('AB', [1, 2])
pd.concat([df1, df3], axis=0)

A   B
1  A1  B1
2  A2  B2
1  A1  B1
2  A2  B2

In [15]:
pd.concat([df1, df3], axis=1)

A   B   A   B
1  A1  B1  A1  B1
2  A2  B2  A2  B2

In [16]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])
print(x); print(y);
y.index = x.index
print(x); print(y);

    A   B
0  A0  B0
1  A1  B1
    A   B
2  A2  B2
3  A3  B3
    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3


In [17]:
print(pd.concat([x, y]))

    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3


In [18]:
try:
    pd.concat([x, y], verify_integrity=True)
except ValueError as e:
    print('Value Error:', e)

Value Error: Indexes have overlapping values: Int64Index([0, 1], dtype='int64')


In [19]:
pd.concat([x, y], ignore_index=True)

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [20]:
pd.concat([x, y], keys=['x', 'y'])

A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3

In [21]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])
print(df5); print(df6);

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4


In [22]:
pd.concat([df5, df6])

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [23]:
pd.concat([df5, df6], join='inner')

B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [24]:
pd.concat([df5, df6], join_axes=[df5.columns])

TypeError: concat() got an unexpected keyword argument 'join_axes'

In [25]:
df1.append(df2)

A    B    C    D
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   C3   D3
4  NaN  NaN   C4   D4